name: system_monitor
description: A package to monitor system CPU and RAM usage.
version: 1.0.0
homepage: https://github.com/14h4i/system_monitor
repository: https://github.com/14h4i/system_monitor

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

example:
  path: example

flutter:
  uses-material-design: true
